# Generated by Django 5.2.7 on 2026-07-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_type',
            field=models.CharField(blank=True, choices=[('bill', 'Bill'), ('receipt', 'Receipt'), ('photo', 'Photo')], max_length=10, null=True),
        ),
    ]
