# Generated by Django 5.2.7 on 2026-07-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_add_ocr_recurring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
