# Generated by Django 5.2.7 on 2026-07-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_add_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
