# Generated by Django 5.2.7 on 2026-07-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_settlementpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementpayment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='splitbill',
            name='expense',
            field=models.ForeignKey(blank=True, help_text='Link to an existing expense (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splits', to='trip.expense'),
        ),
    ]
